# -*- coding: utf-8 -*-
"""aula0python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d_TsRyWPBfexzFhm_2_A5XQ65tJuxNTb
"""

print('aula de python')

print ('aula de python')

nome = 'gabi'
nome

nome = ('gabi')
nome

nome = 'gabi'

nome

livro_da_biblia = 'jó'
livro_da_biblia

print ('o livro favorito da' nome 'é'livro_da_biblia)

print('o livro favorito da ', nome, 'é ', livro_da_biblia)

print ('o livro favorito da' + nome - 'é' + livro_da_biblia)

print ('o livro favorito da {} é {}'.format(nome, livro_da_biblia))

idade = 18
# se idade maior que 18
if idade >= 18:
  print ('pode dirigir!')
# pode dirigir
# senão
else:
# nao pode dirigir
  print ('não pode dirigir!')